version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "pip"
    directory: "/release_creation/bundle/requirements"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
