# **what?**
# This workflow will....

# **why?**
# Because I said so

# **when?**
# This is triggered manually

# **how**
# - poorly

name: Release a Snapshot
permissions:
  packages: read
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: The release version number (i.e. 1.0.0b1).
        required: true
        default: v1.3.0

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_VERSION: ${{ inputs.version_number }}
      GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: |
          sudo apt-get install libsasl2-dev
          python -m pip install --user --upgrade pip
          python -m pip install --upgrade setuptools wheel twine check-wheel-contents
          pip install -r requirements.txt
      - run: python release_creation/main.py
