# **what?**
# This workflow generates a dev bundle release

# **why?**
# We want to be able to test and develop against the latest dbt-* packages

# **when?**
# This is currently triggered manually.

# **how**
# Call workflow dispatch.

name: Release Dev Bundle
permissions:
  packages: read
  contents: write
  pull-requests: read

on:
  schedule:
    - cron: "0 22 * * 1-5" # 10pm UTC on Monday through Friday

  workflow_dispatch:

  workflow_call:

jobs:
  release-new-dev-bundle:
    name: "Release dev bundle"
    uses: ./.github/workflows/release_new_bundle.yml
    with:
      version_number: "0.0.0"

  swap-dev-bundle:
    name: "Swap Dev Bundle"
    runs-on: ubuntu-latest
    needs: [release-new-dev-bundle]
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Swap Dev Bundle"
        run: |
          ./.github/scripts/swap_dev_bundle.sh ${{ needs.release-new-dev-bundle.outputs.tag }}
