# **what?**
# This workflow creates bundles for the supported versions of dbt
# This maps a semver string like "1.0.1" to a requirements file like
# "v1.1.latest.requirements.txt".

# **why?**
# We want to regularly pull in and test updates to dbt and its dependencies

# **when?**
# Every Monday morning

# **how**
# Iterate over the list of bundles and invoke the release_bundle.yml workflow

name: Schedule Bundle Releases

on:
  schedule:
    - cron: "0 22 * * 4" # 10pm UTC on Thursday
  workflow_dispatch:

jobs:
  release-bundles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       # we support the trailing four versions plus the latest pre-release
       # and the upcoming version's pre-release.
       version: ["1.1.0", "1.2.0", "1.3.0", "1.4.0", "1.5.0", "1.6.0b2"]
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3   
        
      - name: Call Release Workflow for ${{ matrix.version }}
        uses: ./.github/workflows/release_bundle.yml
        with:
          version_number: ${{ matrix.version }}
